###############################################################################
## Stigmee: A 3D browser and decentralized social network.
## Copyright 2021 Quentin Quadrat <lecrapouille@gmail.com>
##
## This file is part of Stigmee.
##
## Stigmee is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

name: Compile and release Stigmee on GitHub
on:
  workflow_dispatch:
    branches:
      - master

env:
  WORKSPACE_STIGMEE: ${{ github.workspace }}\workspace_stigmee

jobs:
  #############################################################################
  ### Windows
  #############################################################################
  export_windows:
    runs-on: windows-2022
    steps:

    # Add path for finding cl.exe
    # FIXME: I dunno why Godot editor and godot-cpp can find cl.exe while our
    # godot native modules cannot find it without this extra path
    - uses: ilammy/msvc-dev-cmd@v1.10.0

    - name: Installing Python3 packages
      shell: powershell
      run: |
        echo ${{ env.WORKSPACE_STIGMEE }}
        python3 -m pip install packaging python3_wget scons tsrc pysftp

    - name: Cloning Stigmee project
      shell: powershell
      run: |
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf git@github.com:
        mkdir -p ${{ env.WORKSPACE_STIGMEE }}
        cd ${{ env.WORKSPACE_STIGMEE }}
        tsrc init git@github.com:stigmee/manifest.git
        tsrc sync

    - name: Compiling Stigmee project in release mode
      shell: powershell
      run: |
        cd ${{ env.WORKSPACE_STIGMEE }}
        .\build.py

  #############################################################################
  ### Linux
  #############################################################################
  export_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Update system packages
      run: |
        sudo apt-get update
        sudo apt-get install xvfb

    - name: Installing Python3 packages
      run: |
        sudo apt-get update
        python3 -m pip install packaging python3_wget scons tsrc pysftp

    - name: Cloning Stigmee project
      run: |
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf git@github.com:
        mkdir -p ${{ env.WORKSPACE_STIGMEE }}
        cd ${{ env.WORKSPACE_STIGMEE }}
        tsrc init git@github.com:stigmee/manifest.git
        tsrc sync

    - name: Compiling Stigmee project in release mode
      run: |
        sudo /usr/bin/Xvfb :0 -screen 0 800x600x32 &
        cd ${{ env.WORKSPACE_STIGMEE }}
        ./build.py
